name: Build & Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

    - name: Set up Go
      uses: actions/setup-go@dca8468d37b6d090cde2c7b97b738a37134f5ffb
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Set up Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install Go dependencies
      run: go mod download

    - name: Install Frontend dependencies
      working-directory: frontend
      run: npm ci

    - name: Backend Lint
      uses: golangci/golangci-lint-action@9551b25870123cbad297208ba05e4f0f2b0ffd59
      with:
        version: latest
        args: --timeout=5m

    - name: Frontend Lint
      working-directory: frontend
      run: npm run lint

    - name: Go Tests
      run: go test ./... -v

    - name: Wails Build
      run: go run github.com/wailsapp/wails/v2 build