name: Prepare Winget Submission

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v0.0.10)'
        required: true
      full_version:
        description: 'Full version (e.g., 2025.0.0.10)'
        required: true
      sha256:
        description: 'SHA256 hash of the installer (from release notes)'
        required: true

jobs:
  prepare-winget:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install WinGet
        uses: Cyberboss/install-winget@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check if package exists
        id: check_package
        shell: pwsh
        run: |
          $Publisher = "gomarcd"
          $AppName = "${{ secrets.APP_NAME }}"
          $PackageId = "$Publisher.$AppName"
          Write-Host "Checking if package $PackageId already exists in Winget..."
          $searchOutput = & winget search --exact $PackageId 2>&1
          $exitCode = $LASTEXITCODE
          if ($exitCode -eq 0) {
            Write-Host "Package found in Winget repository!"
            Write-Host "This appears to be an update to an existing package."
            echo "package_exists=true" >> $env:GITHUB_OUTPUT
            echo "action=update" >> $env:GITHUB_OUTPUT
            Write-Host "Available versions:"
            winget show $PackageId
          } else {
            Write-Host "Package not found in Winget repository (Exit code: $exitCode)"
            Write-Host "This appears to be a new package submission."
            echo "package_exists=false" >> $env:GITHUB_OUTPUT
            echo "action=new" >> $env:GITHUB_OUTPUT
            exit 0
          }
        
      - name: Create Manifest
        shell: pwsh
        run: |
          # Create manifest directory structure
          $AppName = "${{ secrets.APP_NAME }}"
          $Publisher = "gomarcd"
          $Version = "${{ github.event.inputs.full_version }}"
          $FirstLetter = $Publisher.Substring(0,1).ToLower()
          $Hash = "${{ github.event.inputs.sha256 }}"
          $Action = "${{ steps.check_package.outputs.action }}"
          
          $manifestPath = "manifests\$FirstLetter\$Publisher\$AppName\$Version"
          New-Item -Path $manifestPath -ItemType Directory -Force
          
          # Use the correct file naming pattern
          $installerFileName = "${AppName}_${Version}_amd64_installer.exe"
          
          # Create the YAML file line by line
          $lines = @()
          $lines += "PackageIdentifier: $Publisher.$AppName"
          $lines += "PackageVersion: $Version"
          $lines += "PackageName: $AppName"
          $lines += "Publisher: $Publisher"
          $lines += "License: MIT"
          $lines += "LicenseUrl: https://github.com/${{ github.repository }}/blob/main/LICENSE"
          $lines += "ShortDescription: The fast, minimal API tool"
          $lines += "Description: $AppName is a modern, cross-platform API client built for developers who need a simple tool for testing APIs."
          $lines += "PackageUrl: https://github.com/${{ github.repository }}"
          $lines += "Installers:"
          $lines += "  - Architecture: x64"
          $lines += "    InstallerType: exe"
          $lines += "    InstallerUrl: https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.tag }}/$installerFileName"
          $lines += "    InstallerSha256: $Hash"
          $lines += "    InstallerSwitches:"
          $lines += "      Silent: /S"
          $lines += "      SilentWithProgress: /S"
          $lines += "ManifestType: singleton"
          $lines += "ManifestVersion: 1.0.0"
          
          # Write the lines to the file
          Set-Content -Path "$manifestPath\$Publisher.$AppName.yaml" -Value $lines
          
          Write-Host "Manifest file created at: $manifestPath\$Publisher.$AppName.yaml"
          Get-Content "$manifestPath\$Publisher.$AppName.yaml"
      
      - name: Upload Manifest
        uses: actions/upload-artifact@v4
        with:
          name: winget-submission
          path: manifests
          retention-days: 7
          
      - name: Provide Submission Instructions
        shell: pwsh
        run: |
          $action = "${{ steps.check_package.outputs.action }}"
          $packageExists = "${{ steps.check_package.outputs.package_exists }}" -eq "true"
          
          Write-Host "==== WINGET SUBMISSION INSTRUCTIONS ===="
          Write-Host "Package check result: $($packageExists ? 'Package exists' : 'New package')"
          Write-Host "Submission type: $action"
          Write-Host ""
          Write-Host "1. Download the 'winget-submission' artifact"
          Write-Host "2. Extract the contents"
          Write-Host "3. Fork the microsoft/winget-pkgs repository"
          Write-Host "4. Copy the manifests directory structure to your fork"
          Write-Host "5. Create a branch for your submission"
          
          if ($packageExists) {
            Write-Host "6. Commit with message 'Update gomarcd.Crashtest to ${{ github.event.inputs.full_version }}'"
          } else {
            Write-Host "6. Commit with message 'Add gomarcd.Crashtest version ${{ github.event.inputs.full_version }}'"
          }
          
          Write-Host "7. Create a pull request to microsoft/winget-pkgs"
          Write-Host "8. Monitor the PR for any validation feedback"
          Write-Host "==== END INSTRUCTIONS ===="