name: Test Winget Submission

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v0.0.10)'
        required: true
      full_version:
        description: 'Full version (e.g., 2025.0.0.10)'
        required: true

jobs:
  test-winget:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install YamlCreate.ps1
        run: |
          # Clone the Windows Package Manager repository to get YamlCreate.ps1
          git clone --depth 1 https://github.com/microsoft/winget-pkgs.git
          
          # Verify the script exists
          if (Test-Path winget-pkgs\Tools\YamlCreate.ps1) {
            Write-Host "YamlCreate.ps1 found!"
          } else {
            Write-Host "YamlCreate.ps1 not found!"
            exit 1
          }
      
      - name: Create Manifest
        shell: pwsh
        run: |
          # Create manifest directory structure
          $AppName = "${{ secrets.APP_NAME }}"
          $Publisher = "gomarcd"
          $Version = "${{ github.event.inputs.full_version }}"
          $FirstLetter = $Publisher.Substring(0,1).ToLower()
          
          $manifestPath = "manifests\$FirstLetter\$Publisher\$AppName\$Version"
          New-Item -Path $manifestPath -ItemType Directory -Force
          
          # Create the YAML file using PowerShell
          $yamlContent = @"
PackageIdentifier: $Publisher.$AppName
PackageVersion: $Version
PackageName: $AppName
Publisher: $Publisher
License: MIT
LicenseUrl: https://github.com/${{ github.repository }}/blob/main/LICENSE
ShortDescription: The fast, minimal API tool
Description: $AppName is a fast, minimal API client designed with privacy and security in mind.
PackageUrl: https://github.com/${{ github.repository }}
Installers:
  - Architecture: x64
    InstallerType: exe
    InstallerUrl: https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.tag }}/${AppName}_${Version}_amd64-installer.exe
    InstallerSha256: placeholder_for_sha256
    InstallerSwitches:
      Silent: /S
      SilentWithProgress: /S
ManifestType: singleton
ManifestVersion: 1.0.0
"@
          
          $yamlContent | Out-File -FilePath "$manifestPath\$Publisher.$AppName.yaml" -Encoding utf8
          
          Write-Host "Manifest file created at: $manifestPath\$Publisher.$AppName.yaml"
          Get-Content "$manifestPath\$Publisher.$AppName.yaml"
      
      - name: Upload Manifest
        uses: actions/upload-artifact@v4
        with:
          name: winget-submission
          path: manifests
          retention-days: 7