name: Test Winget Submission

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v0.0.10)'
        required: true
      full_version:
        description: 'Full version (e.g., 2025.0.0.10)'
        required: true

jobs:
  test-winget:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create Manifest
        shell: pwsh
        run: |
          # Create manifest directory structure
          $AppName = "${{ secrets.APP_NAME }}"
          $Publisher = "gomarcd"
          $Version = "${{ github.event.inputs.full_version }}"
          $FirstLetter = $Publisher.Substring(0,1).ToLower()
          
          $manifestPath = "manifests\$FirstLetter\$Publisher\$AppName\$Version"
          New-Item -Path $manifestPath -ItemType Directory -Force
          
          # Create the YAML file line by line
          $lines = @()
          $lines += "PackageIdentifier: $Publisher.$AppName"
          $lines += "PackageVersion: $Version"
          $lines += "PackageName: $AppName"
          $lines += "Publisher: $Publisher"
          $lines += "License: MIT"
          $lines += "LicenseUrl: https://github.com/${{ github.repository }}/blob/main/LICENSE"
          $lines += "ShortDescription: The fast, minimal API tool"
          $lines += "Description: $AppName is a fast, minimal API client designed with privacy and security in mind."
          $lines += "PackageUrl: https://github.com/${{ github.repository }}"
          $lines += "Installers:"
          $lines += "  - Architecture: x64"
          $lines += "    InstallerType: exe"
          $lines += "    InstallerUrl: https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.tag }}/${AppName}_${Version}_amd64-installer.exe"
          $lines += "    InstallerSha256: placeholder_for_sha256"
          $lines += "    InstallerSwitches:"
          $lines += "      Silent: /S"
          $lines += "      SilentWithProgress: /S"
          $lines += "ManifestType: singleton"
          $lines += "ManifestVersion: 1.0.0"
          
          # Write the lines to the file
          Set-Content -Path "$manifestPath\$Publisher.$AppName.yaml" -Value $lines
          
          Write-Host "Manifest file created at: $manifestPath\$Publisher.$AppName.yaml"
          Get-Content "$manifestPath\$Publisher.$AppName.yaml"
      
      - name: Upload Manifest
        uses: actions/upload-artifact@v4
        with:
          name: winget-submission
          path: manifests
          retention-days: 7