name: Release Crashtest
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  determine-platforms:
    runs-on: ubuntu-latest
    outputs:
      build-windows: ${{ steps.check-tag.outputs.build-windows }}
      build-darwin: ${{ steps.check-tag.outputs.build-darwin }}
      build-linux: ${{ steps.check-tag.outputs.build-linux }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Determine platforms to build
        id: check-tag
        run: |
          TAG_NAME="${{ github.ref_name }}"
          # Standard version tag builds all platforms
          if [[ "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "build-windows=true" >> $GITHUB_OUTPUT
            echo "build-darwin=true" >> $GITHUB_OUTPUT
            echo "build-linux=true" >> $GITHUB_OUTPUT
          # Platform-specific tags
          elif [[ "$TAG_NAME" =~ -win$ ]]; then
            echo "build-windows=true" >> $GITHUB_OUTPUT
            echo "build-darwin=false" >> $GITHUB_OUTPUT
            echo "build-linux=false" >> $GITHUB_OUTPUT
          elif [[ "$TAG_NAME" =~ -mac$ ]]; then
            echo "build-windows=false" >> $GITHUB_OUTPUT
            echo "build-darwin=true" >> $GITHUB_OUTPUT
            echo "build-linux=false" >> $GITHUB_OUTPUT
          elif [[ "$TAG_NAME" =~ -linux$ ]]; then
            echo "build-windows=false" >> $GITHUB_OUTPUT
            echo "build-darwin=false" >> $GITHUB_OUTPUT
            echo "build-linux=true" >> $GITHUB_OUTPUT
          else
            # Default to all platforms for other tag formats
            echo "build-windows=true" >> $GITHUB_OUTPUT
            echo "build-darwin=true" >> $GITHUB_OUTPUT
            echo "build-linux=true" >> $GITHUB_OUTPUT
          fi

  build-windows:
    needs: determine-platforms
    if: ${{ needs.determine-platforms.outputs.build-windows == 'true' }}
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
          check-latest: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
          cd ..

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Create artifacts directory
        run: mkdir -p build/artifacts

      - name: Build Application Windows
        shell: pwsh
        run: |
          wails build -trimpath -o Crashtest_windows_amd64.exe
          Copy-Item -Path build/bin/Crashtest_windows_amd64.exe -Destination build/artifacts/Crashtest_windows_amd64.exe

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Crashtest_windows_amd64.exe
          path: build/artifacts/Crashtest_windows_amd64.exe
          retention-days: 1

  build-darwin:
    needs: determine-platforms
    if: ${{ needs.determine-platforms.outputs.build-darwin == 'true' }}
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
          check-latest: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
          cd ..

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Create artifacts directory
        run: mkdir -p build/artifacts

      - name: Build Application Darwin
        shell: bash
        run: |
          wails build -trimpath -platform darwin/universal
          if [ -d build/bin/Crashtest.app ]; then
            cd build/bin
            zip -r Crashtest_darwin_universal.zip Crashtest.app
            cd ../..
            cp build/bin/Crashtest_darwin_universal.zip build/artifacts/Crashtest_darwin_universal.zip
          else
            echo "Build output not found for Darwin"
            exit 1
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Crashtest_darwin_universal.zip
          path: build/artifacts/Crashtest_darwin_universal.zip
          retention-days: 1

  build-linux:
    needs: determine-platforms
    if: ${{ needs.determine-platforms.outputs.build-linux == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
          check-latest: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
          cd ..

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Create artifacts directory
        run: mkdir -p build/artifacts

      - name: Build Application Linux
        shell: bash
        run: |
          wails build -trimpath -tags webkit2_41 -o Crashtest_linux_amd64
          cp build/bin/Crashtest_linux_amd64 build/artifacts/Crashtest_linux_amd64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Crashtest_linux_amd64
          path: build/artifacts/Crashtest_linux_amd64
          retention-days: 1

  release:
    needs: [build-windows, build-darwin, build-linux]
    runs-on: ubuntu-latest
    if: always()
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Prepare artifacts for release
        run: |
          mkdir -p ./release
          find ./artifacts -type f -exec cp {} ./release/ \;
          ls -l ./release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}