name: Release

on:
  push:
    tags: [ v* ]

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'darwin/universal'
            os: 'macos-latest'
            artifact-suffix: 'mac'
          - platform: 'linux/amd64'
            os: 'ubuntu-latest'
            artifact-suffix: 'linux'
          - platform: 'windows/amd64'
            os: 'windows-latest'
            artifact-suffix: 'windows'

    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Copy gon config into expected path
        if: runner.os == 'macOS'
        run: |
          mkdir -p build/darwin
          cp gon-sign.json build/darwin/gon-sign.json
          cp gon-notarize.json build/darwin/gon-notarize.json

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV


      ###################################### TEMPORARY DEBUGGING
      - name: Verify APPLE_CERTIFICATE is set
        shell: bash
        run: |
          if [ -z "$APPLE_CERTIFICATE" ]; then
            echo "APPLE_CERTIFICATE is empty!"
            exit 1
          else
            echo "APPLE_CERTIFICATE is set and its length is ${#APPLE_CERTIFICATE}"
          fi
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}

      - name: Debug certificate snippet
        shell: bash
        run: echo "${APPLE_CERTIFICATE:0:50}"
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}

      - name: Debug APPLE_DEVELOPER_ID_CERT
        shell: bash
        run: |
          echo "APPLE_DEVELOPER_ID_CERT length: ${#APPLE_DEVELOPER_ID_CERT}"
          echo "APPLE_DEVELOPER_ID_CERT snippet: ${APPLE_DEVELOPER_ID_CERT:0:50}"
        env:
          APPLE_DEVELOPER_ID_CERT: ${{ secrets.APPLE_DEVELOPER_ID_CERT }}

      ###################################### TEMPORARY DEBUGGING

      - name: Wails Build
        uses: dAppServer/wails-build-action@1ed9cb68d194cf664ce7603fdfa353f287fa981f
        with:
          build-name: ${{ secrets.APP_NAME }}
          build-platform: ${{ matrix.platform }}
          package: false
          nsis: ${{ matrix.os == 'windows-latest' }}
          sign: ${{ (matrix.platform == 'darwin/universal' && secrets.APPLE_CERTIFICATE != '') || (matrix.platform == 'windows/amd64' && secrets.WINDOWS_CERTIFICATE_DATA != '') }}
          go-version: '1.23'
          sign-macos-app-id: ${{ secrets.APPLE_DEVELOPER_ID_CERT }}
          sign-macos-app-cert: ${{ secrets.APPLE_CERTIFICATE }}
          sign-macos-app-cert-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          sign-macos-installer-cert: ${{ secrets.APPLE_CERTIFICATE }}
          sign-macos-installer-cert-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          sign-macos-apple-password: ${{ secrets.APPLE_ID_PASS }}
          sign-windows-cert: ${{ secrets.WINDOWS_CERTIFICATE_DATA }}
          sign-windows-cert-password: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}

      - name: Prepare release artifacts
        shell: bash
        run: |
          mkdir -p release
          if [[ "${{ matrix.platform }}" == "darwin/universal" ]]; then
            cp build/bin/${{ secrets.APP_NAME }}.app.zip release/${{ secrets.APP_NAME }}${{ env.VERSION }}_universal.zip
            if [ -f build/bin/${{ secrets.APP_NAME }}.dmg ]; then
              cp build/bin/${{ secrets.APP_NAME }}.dmg release/${{ secrets.APP_NAME }}_${{ env.VERSION }}_universal.dmg
            fi
          elif [[ "${{ matrix.platform }}" == "linux/amd64" ]]; then
            cp build/bin/${{ secrets.APP_NAME }} release/${{ secrets.APP_NAME }}_${{ env.VERSION }}_amd64
          elif [[ "${{ matrix.platform }}" == "windows/amd64" ]]; then
            cp build/bin/${{ secrets.APP_NAME }}.exe release/${{ secrets.APP_NAME }}_${{ env.VERSION }}_amd64.exe
            if ls build/bin/*-amd64-installer.exe 1> /dev/null 2>&1; then
              cp build/bin/*-amd64-installer.exe release/${{ secrets.APP_NAME }}_${{ env.VERSION }}_amd64_installer.exe
            fi
          fi
          cd release
          shasum -a 256 * > SHA256SUMS.txt
          ls -la

      - name: Import GPG key
        run: echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: GPG sign each artifact
        run: |
          for file in release/*; do
            gpg --batch --yes --detach-sign --output "$file.sig" "$file"
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ secrets.APP_NAME }} ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
          files: release/**
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}